# https://docs.docker.com/compose/compose-file/05-services/
services:

  api:
    image: gcc:13.2.0
    user: dev
    entrypoint:
      - sleep
      - infinity
    init: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
