# https://docs.docker.com/compose/compose-file/05-services/
services:

  aide:
    image: gcc:13.2.0
    environment:
      - XMAKE_ROOT=y
    entrypoint:
      - sleep
      - infinity
    init: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
