#!/bin/sh

# Swap-Word
code --install-extension davidmart.swap-word

# VS Sequential Number
code --install-extension neptunedesign.vs-sequential-number

# Git Graph
code --install-extension mhutchie.git-graph

# Http Server
code --install-extension zt5.http-server

# Makefile Tools
code --install-extension ms-vscode.makefile-tools

# AsciiDoc
code --install-extension asciidoctor.asciidoctor-vscode
code --install-extension abhatt-rh.snippets-for-asciidoc
